name: Python CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Загрузка кода
      - uses: actions/checkout@v4

      # 2. Настройка Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 4. Установка зависимостей
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5. Проверка стиля кода (Pylint)
      - name: Run Pylint
        run: pylint main.py

      # 6. Анализ безопасности (Bandit)
      - name: Run Bandit
        run: bandit -r main.py

      # 7. Пример теста (опционально)
      - name: Run tests
        run: echo "Тесты пройдены"